default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: cost_sheet_development

test:
  <<: *default
  database: cost_sheet_test
